all_atoms: false
asyncronous_noise_schedule: false
atom_max_neighbors: 8
atom_radius: 5
backbone_loss_weight: 0
batch_size: 16
c_alpha_max_neighbors: 24
cache_path: /data/rsg/chemistry/gcorso/ligbind/cache
chain_cutoff: 10.0
combined_training: true
confidence_dropout: 0.0
confidence_no_batchnorm: false
confidence_weight: 0.33
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
dataloader_drop_last: false
dataset: generalisation
depthwise_convolution: false
distance_embed_dim: 32
double_val: true
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embed_also_ligand: true
embedding_scale: 1000
embedding_type: sinusoidal
enforce_timesplit: true
esm_embeddings_model: null
freeze_params: 0
high_confidence_threshold: 5.0
include_confidence_prediction: false
include_miscellaneous_atoms: false
inf_pocket_cutoff: 5
inf_pocket_knowledge: false
inference_earlystop_goal: max
inference_earlystop_metric: valinf2_rmsds_lt2
inference_samples: 5
inference_steps: 20
limit_complexes: 0
log_dir: workdir
lr: 0.001
lr_start_factor: 0.001
matching_maxiter: 20
matching_popsize: 20
matching_tries: 1
max_lig_size: null
max_radius: 5.0
max_receptor_size: 1000
merge_clusters: 3
min_ligand_size: 2
moad_dir: data/BindingMOAD_2020_ab_processed_biounit/
moad_esm_embeddings_path: /data/rsg/nlp/gcorso/ligbind/data/BindingMOAD_2020_ab_processed_biounit/moad_sequences_new.pt
moad_esm_embeddings_sequences_path: /data/rsg/nlp/gcorso/ligbind/data/BindingMOAD_2020_ab_processed_biounit/sequences_to_id.fasta
n_epochs: 1000
no_aminoacid_identities: false
no_batch_norm: false
no_differentiate_convolutions: false
no_torsion: false
norm_by_sigma: false
not_fixed_center_conv: false
not_fixed_knn_radius_graph: false
not_full_dataset: false
not_knn_only_graph: false
ns: 32
num_conformers: 1
num_conv_layers: 5
num_dataloader_workers: 1
num_inference_complexes: 500
num_prot_emb_layers: 3
num_workers: 1
nv: 6
odd_parity: false
pdbbind_dir: /data/rsg/chemistry/gcorso/ligbind/data/PDBBind_processed/
pdbbind_esm_embeddings_path: /data/rsg/nlp/hstark/ligbind/data/esm2_3billion_embeddings.pt
pdbsidechain_dir: data/pdb_2021aug02
pdbsidechain_esm_embeddings_path: /data/rsg/nlp/gcorso/ligbind/data/pdb_2021aug02/pdb_sequences_esm_20k.pt
pdbsidechain_esm_embeddings_sequences_path: /data/rsg/nlp/gcorso/ligbind/data/pdb_2021aug02/sequences_to_id.fasta
pin_memory: false
pocket_mode_graph: false
pretrain_ckpt: null
pretrain_dir: null
project: gen_train
protein_file: protein_processed
receptor_radius: 15.0
reduce_pseudoscalars: true
remove_hs: true
remove_promiscuous_targets: 1
remove_second_segment: false
restart_ckpt: last_model
restart_dir: null
restart_lr: null
rot_alpha: 1.0
rot_beta: 1.0
rot_sigma_max: 3.1
rot_sigma_min: 0.06
rot_weight: 0.33
run_name: triple_m3_time_gen_lmax1_alpha2_protligemb3_reducepseudo
sampling_alpha: 2.0
sampling_beta: 1.0
save_model_freq: null
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
separate_noise_schedule: false
sh_lmax: 1
sidechain_loss_weight: 0
sigma_embed_dim: 32
smooth_edges: false
split_test: data/splits/timesplit_test
split_train: /data/rsg/chemistry/gcorso/ligbind/data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test_sigma_intervals: true
tor_alpha: 1.0
tor_beta: 1.0
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
torsional_data_dir: ../../confgen/confgen/data/QM9/qm9/
torsional_split_path: ../../confgen/confgen/data/QM9/splits/split0.npy
tp_weights_layers: 2
tr_only_confidence: true
tr_sigma_max: 19.0
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: 20
train_multiplicity: 1
triple_training: true
unroll_clusters: true
use_ema: true
use_full_size_protein_file: false
use_old_atom_encoder: false
use_old_wrong_embedding_order: false
use_second_order_repr: false
val_inference_freq: 5
val_multiplicity: 1
vandermers_buffer_residue_num: 10
vandermers_max_dist: 5
vandermers_min_contacts: 5
w_decay: 0.0
wandb: true
warmup_dur: 4
