affinity_prediction: false
all_atoms: true
asyncronous_noise_schedule: false
atom_confidence_loss_weight: 0.5
atom_max_neighbors: 8
atom_radius: 5
atom_rmsd_classification_cutoff: 2.0
balance: true
batch_size: 16
best_model_save_frequency: 5
c_alpha_max_neighbors: 24
cache_creation_id: 5
cache_ids_to_combine:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
cache_path: /data/rsg/chemistry/gcorso/ligbind/cache
chain_cutoff: 10.0
ckpt: best_ema_inference_epoch_model.pt
confidence_dropout: 0.0
confidence_loss_weight: 1
confidence_no_batchnorm: false
config: null
correct_torsion_sigmas: true
crop_beyond: 20.0
cross_distance_embed_dim: 32
cross_max_distance: 80
dataloader_drop_last: true
dataset: moad
different_schedules: false
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
embedding_scale: 10000
embedding_type: sinusoidal
esm_embeddings_path: /data/rsg/chemistry/gcorso/ligbind/data/esm2_3billion_embeddings.pt
grad_clip: null
high_confidence_threshold: 5.0
include_confidence_prediction: false
inf_sched_alpha: 1.0
inf_sched_beta: 1.0
inference_steps: 20
limit_complexes: 0
lm_embeddings_path: null
log_dir: workdir
lr: 0.0003
main_metric: accuracy
main_metric_goal: max
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
max_receptor_size: null
min_ligand_size: 0
moad_dir: data/BindingMOAD_2020_ab_processed_biounit/
moad_esm_embeddings_path: /data/rsg/nlp/gcorso/ligbind/data/BindingMOAD_2020_ab_processed_biounit/moad_sequences_new.pt
moad_esm_embeddings_sequences_path: /data/rsg/nlp/gcorso/ligbind/data/BindingMOAD_2020_ab_processed_biounit/sequences_to_id.fasta
model_save_frequency: 0
multiplicity: 1
multiplicity_test: 1
n_epochs: 300
no_batch_norm: false
no_torsion: false
no_train: false
norm_by_sigma: false
not_fixed_knn_radius_graph: false
not_full_dataset: false
not_knn_only_graph: false
ns: 24
num_conformers: 1
num_conv_layers: 5
num_workers: 1
nv: 6
odd_parity: false
original_model_dir: /data/rsg/nlp/gcorso/ligbind/workdir/triple_m3_time_gen_lmax1_alpha2_protligemb3_reducepseudo
parallel: 1
parallel_aggregators: mean max min std
pdbbind_dir: data/PDBBind_processed/
pdbbind_esm_embeddings_path: null
project: ligbind_filtering
protein_file: protein_processed
receptor_radius: 15.0
remove_hs: true
remove_pdbbind: false
remove_promiscuous_targets: null
restart_dir: null
rmsd_classification_cutoff: 2.0
rmsd_classification_upper: 4.0
rmsd_prediction: false
rot_alpha: 1
rot_beta: 1
rot_inf_sched_alpha: 1
rot_inf_sched_beta: 1
rot_sigma_schedule: expbeta
rot_sigmoid_schedule: false
run_name: crop20_upper4_atomconf0.5_ncaches10_sched20
samples_per_complex: 4
sampling_alpha: 1
sampling_beta: 1
scale_by_sigma: true
schedule_k: 10
schedule_m: 0.4
scheduler: plateau
scheduler_patience: 20
separate_noise_schedule: false
sigma_embed_dim: 32
sigma_schedule: expbeta
smooth_edges: false
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test: false
tor_alpha: 1
tor_beta: 1
tor_inf_sched_alpha: 1
tor_inf_sched_beta: 1
tor_sigma_schedule: expbeta
tp_attention: false
tr_only_confidence: true
train_sampling: linear
trajectory_training: false
transfer_weights: false
unroll_clusters: true
use_original_model_cache: false
use_second_order_repr: false
val_multiplicity: 4
w_decay: 0.0
wandb: true
