affinity_prediction: false
all_atoms: false
asyncronous_noise_schedule: false
atom_max_neighbors: 8
atom_radius: 5
balance: false
batch_size: 32
best_model_save_frequency: 5
c_alpha_max_neighbors: 24
cache_creation_id: 6
cache_ids_to_combine:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
cache_path: /data/rsg/nlp/hstark/ligbind/data/cacheNew
chain_cutoff: 10
ckpt: best_ema_inference_epoch_model.pt
confidence_dropout: 0.1
confidence_loss_weigth: 1
confidence_no_batchnorm: false
config: null
correct_torsion_sigmas: true
cross_distance_embed_dim: 32
cross_max_distance: 80
data_dir: /data/rsg/nlp/hstark/ligbind/data/PDBBind_processed/
dataloader_drop_last: false
dataset: pdbbind
dedup_func: min
different_schedules: false
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
embedding_scale: 10000
embedding_type: sinusoidal
esm_embeddings_path: null
high_confidence_threshold: 5.0
include_confidence_prediction: false
inf_sched_alpha: 1.0
inf_sched_beta: 1.0
inference_steps: 20
limit_complexes: 0
lm_embeddings_path: null
log_dir: workdir
lr: 0.0003
main_metric: loss
main_metric_goal: min
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
model_save_frequency: 0
multiplicity: 1
n_epochs: 100
no_aminoacid_identities: true
no_batch_norm: false
no_torsion: false
norm_by_sigma: false
normalize_affinity: false
not_fixed_knn_radius_graph: false
not_full_dataset: false
not_knn_only_graph: false
ns: 24
num_conformers: 1
num_conv_layers: 5
num_workers: 1
nv: 6
odd_parity: false
original_model_dir: /data/rsg/nlp/hstark/ligbind/workdir/restart_big_noAminoId
parallel: 1
parallel_aggregators: mean max min std
project: ligbind_filtering
protein_file: protein_processed
rank_affinity: false
rank_cutoff: null
receptor_radius: 15.0
remove_hs: true
restart_dir: null
rmsd_classification_cutoff: 2
rmsd_prediction: false
rot_alpha: 1
rot_beta: 1
rot_inf_sched_alpha: 1
rot_inf_sched_beta: 1
rot_sigma_schedule: expbeta
rot_sigmoid_schedule: false
run_name: noAminoId_confidence_l5s24v6_FILTERFROM_restart_big_noAminoId
samples_per_complex: 3
sampling_alpha: 1
sampling_beta: 1
scale_by_sigma: true
schedule_k: 10
schedule_m: 0.4
scheduler: plateau
scheduler_patience: 20
separate_noise_schedule: false
sigma_embed_dim: 32
sigma_schedule: expbeta
smooth_edges: false
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
temp_psi: 0.0
temp_sampling: 1.0
temp_sigma_data: 0.5
tor_alpha: 1
tor_beta: 1
tor_inf_sched_alpha: 1
tor_inf_sched_beta: 1
tor_sigma_schedule: expbeta
tp_attention: false
tr_only_confidence: true
train_sampling: linear
transfer_weights: false
use_original_model_cache: false
use_second_order_repr: false
w_decay: 0.0
wandb: true
