all_atoms: false
asyncronous_noise_schedule: false
atom_max_neighbors: 8
atom_radius: 5
batch_size: 16
c_alpha_max_neighbors: 24
cache_path: /data/rsg/nlp/hstark/ligbind/data/cacheNew
chain_cutoff: 10
confidence_dropout: 0.0
confidence_no_batchnorm: false
confidence_weight: 0.33
config: null
cross_distance_embed_dim: 64
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/PDBBind_processed/
dataloader_drop_last: false
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: null
high_confidence_threshold: 5.0
include_confidence_prediction: false
inf_pocket_cutoff: 5
inf_pocket_knowledge: false
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
limit_complexes: 0
log_dir: /data/rsg/nlp/hstark/ligbind/workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 1000
no_aminoacid_identities: true
no_batch_norm: false
no_torsion: false
norm_by_sigma: false
not_fixed_center_conv: false
not_full_dataset: false
ns: 48
num_conformers: 1
num_conv_layers: 6
num_dataloader_workers: 1
num_inference_complexes: 500
num_workers: 1
nv: 10
odd_parity: false
pin_memory: true
pocket_mode_graph: false
project: ligbind_train
protein_file: protein_processed
receptor_radius: 15.0
remove_hs: true
restart_dir: /data/rsg/nlp/hstark/ligbind/workdir/big_noAminoId
restart_lr: null
rot_alpha: 1.0
rot_beta: 1.0
rot_sigma_max: 1.55
rot_sigma_min: 0.03
rot_weight: 0.33
run_name: restart_big_noAminoId
sampling_alpha: 2.0
sampling_beta: 1.0
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
separate_noise_schedule: false
sigma_embed_dim: 64
smooth_edges: false
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test_sigma_intervals: true
tor_alpha: 1.0
tor_beta: 1.0
tor_sigma_max: 3.14
tor_sigma_min: 0.03
tor_weight: 0.33
tr_only_confidence: true
tr_sigma_max: 19.0
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
use_ema: true
use_full_size_protein_file: false
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: true
